version: "3.8"
services:
  redis-cache:
    image: redis
    container_name: redis_cache
    ports:
      - 6379:6379
    restart: always
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG

  nginx:
    container_name: load_balancer
    image: nginx:latest
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./docker-configurations/nginx/shortener.test.conf:/etc/nginx/conf.d/default.conf
