POST http://localhost/create HTTP/1.1
content-type: application/json

{
	"longUrl": "https://articulo.mercadolibre.cl/MLC-538236036-termo-cafe-agua-caliente-globalchile-_JM?variation=93744240785#reco_item_pos=0&reco_backend=machinalis-homes&reco_backend_type=function&reco_client=home_navigation-recommendations&reco_id=29d96792-2b7b-4d62-9663-24751defe048&c_id=/home/navigation-recommendations/element&c_element_order=1&c_uid=5b4fbecb-fa2d-43ff-a444-0d2e6d8d52b2"

}


###
GET http://localhost/long-url/dG4fkE HTTP/1.1


###

DELETE http://localhost/22 HTTP/1.1